// Usage: node tests/browser.cjs <installed-playwright-module> <local-url>
const { chromium } = require(process.argv[2] || '@playwright/test');
const assert = require('node:assert/strict');
const { mkdtempSync, mkdirSync, writeFileSync } = require('node:fs');
const { tmpdir } = require('node:os');
const path = require('node:path');
const url = process.argv[3] || 'http://127.0.0.1:51405/';
const profile = mkdtempSync(path.join(tmpdir(), 'sunflower-browser-test-'));
const output = path.resolve(__dirname, '../artifacts');
mkdirSync(output, { recursive: true });
const passed = [], errors = [];
const mark = message => { passed.push(message); console.log('PASS:', message); };
const overallTimeout = setTimeout(() => { console.error('Browser check timed out'); if (context) context.close(); process.exitCode = 1; }, 90000);
const launch = () => chromium.launchPersistentContext(profile, {
  executablePath: chromium.executablePath(), headless: true, viewport: { width: 390, height: 844 }, deviceScaleFactor: 1,
  isMobile: true, hasTouch: true, permissions: ['clipboard-read', 'clipboard-write'],
});
let context;
(async () => {
  context = await launch();
  let page = context.pages()[0];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.locator('.code-card').first().waitFor();
  await page.waitForFunction(() => document.querySelector('#code-list').getAttribute('aria-busy') === 'false');
  const original = await page.evaluate(() => JSON.parse(localStorage.getItem('sunflower.catalog.v1')));
  assert.equal(original.codes.length, 70);
  assert.equal(await page.locator('[data-code="DECN5KD"]').count(), 0);
  assert.equal(await page.locator('.code-card').count(), 67);
  mark('70 codes loaded; 3 expired codes hidden');
  await page.getByRole('button', { name: '复制 V4INKEJ', exact: true }).click();
  await page.bringToFront();
  assert.equal(await Promise.race([page.evaluate(() => navigator.clipboard.readText()), new Promise((_, reject) => setTimeout(() => reject(new Error('clipboard read timeout')), 8000))]), 'V4INKEJ');
  assert.equal(await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).isChecked(), false);
  mark('real clipboard contains exact code; copying does not mark used');
  await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).click();
  assert.equal(await page.locator('[data-code="V4INKEJ"]').count(), 0);
  await page.getByRole('button', { name: '已使用', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).isChecked(), true);
  await context.close();
  context = await launch();
  page = context.pages()[0];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.locator('.code-card').first().waitFor();
  await page.getByRole('button', { name: '已使用', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).isChecked(), true);
  mark('used checkbox survives a real browser close and reopen');
  const refreshed = { ...original, codes: [...original.codes, { code: 'TESTONLY9', sourceType: 'screenshot', firstSeen: '2026-09-15', expiresAt: null }] };
  await page.route('**/data/codes.json?*', route => route.fulfill({ json: refreshed }));
  await page.getByRole('button', { name: '刷新码库' }).click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('sunflower.catalog.v1')).codes.length === 71);
  assert.equal(await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).isChecked(), true);
  mark('incremental update preserves personal used state');
  await page.unroute('**/data/codes.json?*');
  await page.route('**/data/codes.json?*', route => route.fulfill({ json: { codes: [{ code: '<script>' }] } }));
  await page.getByRole('button', { name: '刷新码库' }).click();
  await page.getByText('当前离线或连接失败', { exact: false }).waitFor();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('sunflower.catalog.v1')).codes.length), 71);
  mark('invalid remote data cannot replace cached catalog');
  await page.unroute('**/data/codes.json?*');
  await page.getByRole('button', { name: '刷新码库' }).click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('sunflower.catalog.v1')).codes.length === 70);
  await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).click();
  await page.getByRole('button', { name: '未使用', exact: true }).click();
  await page.evaluate(() => { Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: () => Promise.reject(new Error('test permission denied')) }); });
  await page.getByRole('button', { name: '复制 V4INKEJ', exact: true }).click();
  assert.equal(await page.locator('#manual-copy').isVisible(), true);
  assert.equal(await page.locator('#manual-code').inputValue(), 'V4INKEJ');
  await page.getByRole('button', { name: '完成', exact: true }).click();
  mark('clipboard permission failure opens manual copy fallback');
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('test quota exceeded'); }; });
  await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { name: 'V4INKEJ 已使用', exact: true }).isChecked(), false);
  assert.match(await page.locator('#storage-warning').innerText(), /没有保存/);
  mark('storage failure reports failure and rolls back checkbox');
  await page.reload();
  await page.locator('.code-card').first().waitFor();
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.waitForFunction(() => Boolean(navigator.serviceWorker.controller));
  await context.setOffline(true);
  await page.reload();
  await page.locator('.code-card').first().waitFor();
  await page.getByText('当前离线或连接失败', { exact: false }).waitFor();
  await page.getByRole('checkbox', { name: 'VIP666 已使用', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: '已使用', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { name: 'VIP666 已使用', exact: true }).isChecked(), true);
  mark('offline app reload and offline checkbox persistence work');
  await context.setOffline(false);
  await page.getByRole('checkbox', { name: 'VIP666 已使用', exact: true }).click();
  await page.getByRole('button', { name: '未使用', exact: true }).click();
  await page.getByRole('button', { name: '刷新码库' }).click();
  await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
  await page.evaluate(() => { document.querySelector('#toast').hidden = true; });
  for (const width of [320, 390, 430, 1024]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `overflow at ${width}`);
    if (width === 390) await page.screenshot({ path: path.join(output, 'iphone-preview.png') });
    if (width === 1024) await page.screenshot({ path: path.join(output, 'desktop-preview.png') });
  }
  mark('320 / 390 / 430 / 1024 widths have no horizontal overflow');
  assert.deepEqual(errors, []);
  const result = { browser: 'Chromium mobile emulation, not physical iPhone', passed, runtimeErrors: errors, timestamp: new Date().toISOString() };
  writeFileSync(path.join(output, 'browser-results.json'), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { clearTimeout(overallTimeout); if (context) await context.close(); });
